language: java
jdk:
  - openjdk17
script:
  - mvn verify
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  username: $deploy_username
  password: $deploy_password
  organization: $deploy_org_name
  space: $SPACE_NAME
  manifest: manifest.yml
  on:
    repo: Crown-Commercial-Service/ccs-conclave-data-migration
    branch: $DEPLOY_BRANCH
services:
  - postgresql
addons:
  postgresql: '12'
