language: java
jdk:
  - openjdk17

script:
  - mvn verify

env:
  global:
    - CF_USER=$deploy_username
    - CF_PASS=$deploy_password
    - CF_ORG=$deploy_org_name
    - CF_SPACE=$SPACE_NAME

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  username: $deploy_username
  password: $deploy_password
  organization: $deploy_org_name
  space: $SPACE_NAME
  manifest: manifest.yml
  on:
    repo: Crown-Commercial-Service/ccs-conclave-data-migration
    branch: $DEPLOY_BRANCH

services:
  - postgresql

addons:
  postgresql: '12'

after_deploy:
  - echo "JSON Application Finished Deploying. Check for Success or Failure."
  - echo "Now Deploying CSV Application."
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get -qq update
  - sudo apt-get install cf7-cli
  - bash csv/CF/deploy-app.sh -u $CF_USER -p $CF_PASS -o $CF_ORG -s $CF_SPACE
