/*
 * CCS Central Identity Index Service (CII)
 * This is an example CCS Central Identity Index (CII) Service API.
 *
 * OpenAPI spec version: 1.0.4
 * Contact: apiteam@crowncommercial.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.cii.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.cii.model.Identifier;
import uk.gov.ccs.swagger.cii.model.IdentifierPlusinActive;
/**
 * IdentitiesAll
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-23T17:33:47.049364+01:00[Europe/London]")
public class IdentitiesAll {
  @SerializedName("identifier")
  private Identifier identifier = null;

  @SerializedName("additionalIdentifiers")
  private List<IdentifierPlusinActive> additionalIdentifiers = new ArrayList<IdentifierPlusinActive>();

  public IdentitiesAll identifier(Identifier identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @Schema(required = true, description = "")
  public Identifier getIdentifier() {
    return identifier;
  }

  public void setIdentifier(Identifier identifier) {
    this.identifier = identifier;
  }

  public IdentitiesAll additionalIdentifiers(List<IdentifierPlusinActive> additionalIdentifiers) {
    this.additionalIdentifiers = additionalIdentifiers;
    return this;
  }

  public IdentitiesAll addAdditionalIdentifiersItem(IdentifierPlusinActive additionalIdentifiersItem) {
    this.additionalIdentifiers.add(additionalIdentifiersItem);
    return this;
  }

   /**
   * Get additionalIdentifiers
   * @return additionalIdentifiers
  **/
  @Schema(required = true, description = "")
  public List<IdentifierPlusinActive> getAdditionalIdentifiers() {
    return additionalIdentifiers;
  }

  public void setAdditionalIdentifiers(List<IdentifierPlusinActive> additionalIdentifiers) {
    this.additionalIdentifiers = additionalIdentifiers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentitiesAll identitiesAll = (IdentitiesAll) o;
    return Objects.equals(this.identifier, identitiesAll.identifier) &&
        Objects.equals(this.additionalIdentifiers, identitiesAll.additionalIdentifiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, additionalIdentifiers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentitiesAll {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    additionalIdentifiers: ").append(toIndentedString(additionalIdentifiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
