---
openapi: 3.0.0
info:
  title: CCS Central Identity Index Service (CII)
  description: This is an example CCS Central Identity Index (CII) Service API.
  termsOfService: http://api.crowncommercial.gov.uk/terms/
  contact:
    email: apiteam@crowncommercial.gov.uk
  license:
    name: Open Government Licence 3.0
    url: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
  version: 1.0.4
servers:
- url: https://virtserver.swaggerhub.com/miahnanu/CII/1.0.1
  description: SwaggerHub API Auto Mocking
tags:
- name: identities
  description: Everything about Organisation Identities
  externalDocs:
    description: Find out more
    url: http://apis.crowncommercial.gov.uk
paths:
  /identities/organisations/schemes/{scheme}/identifiers/{id}:
    post:
      tags:
      - identities
      summary: A generic endpoint for regisering organisations from data file supplied by individual CCS platforms and services.
      operationId: app.migrateOrg
      parameters:
      - name: scheme
        in: path
        description: scheme code is the code to the identifier for e.g. GB-COH is Companies House and US-DUNS is Duns and Bradstreet
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: id
        in: path
        description: scheme ID for scheme 05606089
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrgMigration'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "409":
          description: Duplicate resource
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OrgMigration'
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
        "501":
          description: Not Implemented
        "502":
          description: Bad Gateway
        "503":
          description: Service Unavailable/Limit Exceeded
        "504":
          description: Gateway Timeout
        "505":
          description: HTTP Version Not Supported
components:
  schemas:
    OrgMigration:
      type: object
      properties:
        organisationId:
          type: string
          description: id 19700101T000000Z
          example: 19700101T000000Z
        identifier:
          $ref: '#/components/schemas/Identifier'
        additionalIdentifiers:
          type: array
          items:
            $ref: '#/components/schemas/Identifier'
        address:
          $ref: '#/components/schemas/Address'
        contactPoint:
          $ref: '#/components/schemas/ContactPoint'
    Address:
      required:
      - countryName
      - locality
      - postalCode
      - region
      - streetAddress
      type: object
      properties:
        streetAddress:
          type: string
          description: 'The street address. '
          example: For example, 1600 Amphitheatre Pkwy
        locality:
          type: string
          description: The locality.
          example: Mountain View.
        region:
          type: string
          description: 'The region. '
          example: CA.
        postalCode:
          type: string
          description: The postal code.
          example: "94043"
        countryName:
          type: string
          description: The country name.
          example: United States.
    ContactPoint:
      required:
      - email
      - faxNumber
      - name
      - telephone
      - uri
      type: object
      properties:
        name:
          type: string
          description: The name of the contact person, department, or contact point, for correspondence relating to this contracting process
          example: Bob Smith
        email:
          type: string
          description: The e-mail address of the contact point/person.
          example: bob.smith@company.com
        telephone:
          type: string
          description: The telephone number of the contact point/person. This should include the international dialling code.
          example: 020 7777 7777
        faxNumber:
          type: string
          description: The fax number of the contact point/person. This should include the international dialling code.
          example: 020 7777 7777
        uri:
          type: string
          description: A web address for the contact point/person.
          example: www.linkedin.com/in/.......
    Identifier:
      title: Identifier
      type: object
      properties:
        scheme:
          $ref: '#/components/schemas/OrganizationScheme'
        id:
          title: ID
          description: The identifier of the organization in the selected scheme.
          nullable: true
          example: abc12345
          type: string
        legalName:
          title: Legal Name
          type: string
          description: The legally registered name of the organization.
          nullable: true
        uri:
          title: URI
          type: string
          description: 'A URI to identify the organization, such as those provided by [Open Corporates](http://www.opencorporates.com) or some other relevant URI provider. This is not for listing the website of the organization: that can be done through the URL field of the Organization contact point.'
          format: uri
          nullable: true
      description: A unique identifier for a party (organization).
    OrganizationScheme:
      title: Organisation Scheme
      type: string
      description: Organization identifiers should be taken from an existing organization identifier list. The scheme field is used to indicate the list or register from which the identifier is taken. This value should be taken from the [Organization Identifier Scheme](https://standard.open-contracting.org/latest/en/schema/codelists/#organization-identifier-scheme) codelist.
      nullable: true
      example: GB-COH
      enum:
      - GB-COH
      - GB-MPR
      - GB-NIC
      - GB-CHC
      - GB-SC
      - GB-WALEDU
      - GB-SCOTEDU
      - GB-GOR
      - GB-LANI
      - GB-NHS
  securitySchemes:
    cii_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.ccsexample.com/oauth2/authorize
          scopes:
            write:users: modify users in your organisation
            read:users: read users in your organisation
