/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AutoValidationDetails
 */


public class AutoValidationDetails {
  @SerializedName("adminEmailId")
  private String adminEmailId = null;

  @SerializedName("isFromBackgroundJob")
  private Boolean isFromBackgroundJob = null;

  @SerializedName("companyHouseId")
  private String companyHouseId = null;

  public AutoValidationDetails adminEmailId(String adminEmailId) {
    this.adminEmailId = adminEmailId;
    return this;
  }

   /**
   * Get adminEmailId
   * @return adminEmailId
  **/
  @Schema(description = "")
  public String getAdminEmailId() {
    return adminEmailId;
  }

  public void setAdminEmailId(String adminEmailId) {
    this.adminEmailId = adminEmailId;
  }

  public AutoValidationDetails isFromBackgroundJob(Boolean isFromBackgroundJob) {
    this.isFromBackgroundJob = isFromBackgroundJob;
    return this;
  }

   /**
   * Get isFromBackgroundJob
   * @return isFromBackgroundJob
  **/
  @Schema(description = "")
  public Boolean isIsFromBackgroundJob() {
    return isFromBackgroundJob;
  }

  public void setIsFromBackgroundJob(Boolean isFromBackgroundJob) {
    this.isFromBackgroundJob = isFromBackgroundJob;
  }

  public AutoValidationDetails companyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
    return this;
  }

   /**
   * Get companyHouseId
   * @return companyHouseId
  **/
  @Schema(description = "")
  public String getCompanyHouseId() {
    return companyHouseId;
  }

  public void setCompanyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoValidationDetails autoValidationDetails = (AutoValidationDetails) o;
    return Objects.equals(this.adminEmailId, autoValidationDetails.adminEmailId) &&
        Objects.equals(this.isFromBackgroundJob, autoValidationDetails.isFromBackgroundJob) &&
        Objects.equals(this.companyHouseId, autoValidationDetails.companyHouseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminEmailId, isFromBackgroundJob, companyHouseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoValidationDetails {\n");
    
    sb.append("    adminEmailId: ").append(toIndentedString(adminEmailId)).append("\n");
    sb.append("    isFromBackgroundJob: ").append(toIndentedString(isFromBackgroundJob)).append("\n");
    sb.append("    companyHouseId: ").append(toIndentedString(companyHouseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
