/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CallingConventions
 */
@JsonAdapter(CallingConventions.Adapter.class)
public enum CallingConventions {
  NUMBER_1(1),
  NUMBER_2(2),
  NUMBER_3(3),
  NUMBER_32(32),
  NUMBER_64(64);

  private Integer value;

  CallingConventions(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CallingConventions fromValue(String text) {
    for (CallingConventions b : CallingConventions.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "' for 'CallingConventions' enum.");
  }

  public static class Adapter extends TypeAdapter<CallingConventions> {
    @Override
    public void write(final JsonWriter jsonWriter, final CallingConventions enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CallingConventions read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextInt();
      return CallingConventions.fromValue(String.valueOf(value));
    }
  }
}
