/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.AssignedContactType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import uk.gov.ccs.swagger.sso.JSON;

/**
 * ContactAssignmentInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ContactAssignmentInfo {
  public static final String SERIALIZED_NAME_ASSIGNING_CONTACT_TYPE = "assigningContactType";
  @SerializedName(SERIALIZED_NAME_ASSIGNING_CONTACT_TYPE)
  private AssignedContactType assigningContactType;

  public static final String SERIALIZED_NAME_ASSIGNING_CONTACT_POINT_IDS = "assigningContactPointIds";
  @SerializedName(SERIALIZED_NAME_ASSIGNING_CONTACT_POINT_IDS)
  private List<Integer> assigningContactPointIds = null;

  public static final String SERIALIZED_NAME_ASSIGNING_CONTACTS_USER_ID = "assigningContactsUserId";
  @SerializedName(SERIALIZED_NAME_ASSIGNING_CONTACTS_USER_ID)
  private String assigningContactsUserId;

  public static final String SERIALIZED_NAME_ASSIGNING_CONTACTS_SITE_ID = "assigningContactsSiteId";
  @SerializedName(SERIALIZED_NAME_ASSIGNING_CONTACTS_SITE_ID)
  private Integer assigningContactsSiteId;

  public ContactAssignmentInfo() { 
  }

  public ContactAssignmentInfo assigningContactType(AssignedContactType assigningContactType) {
    
    this.assigningContactType = assigningContactType;
    return this;
  }

   /**
   * Get assigningContactType
   * @return assigningContactType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AssignedContactType getAssigningContactType() {
    return assigningContactType;
  }


  public void setAssigningContactType(AssignedContactType assigningContactType) {
    this.assigningContactType = assigningContactType;
  }


  public ContactAssignmentInfo assigningContactPointIds(List<Integer> assigningContactPointIds) {
    
    this.assigningContactPointIds = assigningContactPointIds;
    return this;
  }

  public ContactAssignmentInfo addAssigningContactPointIdsItem(Integer assigningContactPointIdsItem) {
    if (this.assigningContactPointIds == null) {
      this.assigningContactPointIds = new ArrayList<>();
    }
    this.assigningContactPointIds.add(assigningContactPointIdsItem);
    return this;
  }

   /**
   * Get assigningContactPointIds
   * @return assigningContactPointIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getAssigningContactPointIds() {
    return assigningContactPointIds;
  }


  public void setAssigningContactPointIds(List<Integer> assigningContactPointIds) {
    this.assigningContactPointIds = assigningContactPointIds;
  }


  public ContactAssignmentInfo assigningContactsUserId(String assigningContactsUserId) {
    
    this.assigningContactsUserId = assigningContactsUserId;
    return this;
  }

   /**
   * Get assigningContactsUserId
   * @return assigningContactsUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAssigningContactsUserId() {
    return assigningContactsUserId;
  }


  public void setAssigningContactsUserId(String assigningContactsUserId) {
    this.assigningContactsUserId = assigningContactsUserId;
  }


  public ContactAssignmentInfo assigningContactsSiteId(Integer assigningContactsSiteId) {
    
    this.assigningContactsSiteId = assigningContactsSiteId;
    return this;
  }

   /**
   * Get assigningContactsSiteId
   * @return assigningContactsSiteId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAssigningContactsSiteId() {
    return assigningContactsSiteId;
  }


  public void setAssigningContactsSiteId(Integer assigningContactsSiteId) {
    this.assigningContactsSiteId = assigningContactsSiteId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactAssignmentInfo contactAssignmentInfo = (ContactAssignmentInfo) o;
    return Objects.equals(this.assigningContactType, contactAssignmentInfo.assigningContactType) &&
        Objects.equals(this.assigningContactPointIds, contactAssignmentInfo.assigningContactPointIds) &&
        Objects.equals(this.assigningContactsUserId, contactAssignmentInfo.assigningContactsUserId) &&
        Objects.equals(this.assigningContactsSiteId, contactAssignmentInfo.assigningContactsSiteId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigningContactType, assigningContactPointIds, assigningContactsUserId, assigningContactsSiteId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactAssignmentInfo {\n");
    sb.append("    assigningContactType: ").append(toIndentedString(assigningContactType)).append("\n");
    sb.append("    assigningContactPointIds: ").append(toIndentedString(assigningContactPointIds)).append("\n");
    sb.append("    assigningContactsUserId: ").append(toIndentedString(assigningContactsUserId)).append("\n");
    sb.append("    assigningContactsSiteId: ").append(toIndentedString(assigningContactsSiteId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("assigningContactType");
    openapiFields.add("assigningContactPointIds");
    openapiFields.add("assigningContactsUserId");
    openapiFields.add("assigningContactsSiteId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ContactAssignmentInfo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ContactAssignmentInfo.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContactAssignmentInfo is not found in the empty JSON string", ContactAssignmentInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ContactAssignmentInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContactAssignmentInfo` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("assigningContactPointIds") != null && !jsonObj.get("assigningContactPointIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `assigningContactPointIds` to be an array in the JSON string but got `%s`", jsonObj.get("assigningContactPointIds").toString()));
      }
      if (jsonObj.get("assigningContactsUserId") != null && !jsonObj.get("assigningContactsUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assigningContactsUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assigningContactsUserId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContactAssignmentInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContactAssignmentInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContactAssignmentInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContactAssignmentInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<ContactAssignmentInfo>() {
           @Override
           public void write(JsonWriter out, ContactAssignmentInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContactAssignmentInfo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ContactAssignmentInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ContactAssignmentInfo
  * @throws IOException if the JSON string is invalid with respect to ContactAssignmentInfo
  */
  public static ContactAssignmentInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContactAssignmentInfo.class);
  }

 /**
  * Convert an instance of ContactAssignmentInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

