/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import uk.gov.ccs.swagger.sso.model.Type;
/**
 * CustomAttributeTypedArgument
 */


public class CustomAttributeTypedArgument {
  @SerializedName("argumentType")
  private Type argumentType = null;

  @SerializedName("value")
  private Object value = null;

  public CustomAttributeTypedArgument argumentType(Type argumentType) {
    this.argumentType = argumentType;
    return this;
  }

   /**
   * Get argumentType
   * @return argumentType
  **/
  @Schema(description = "")
  public Type getArgumentType() {
    return argumentType;
  }

  public void setArgumentType(Type argumentType) {
    this.argumentType = argumentType;
  }

  public CustomAttributeTypedArgument value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(description = "")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomAttributeTypedArgument customAttributeTypedArgument = (CustomAttributeTypedArgument) o;
    return Objects.equals(this.argumentType, customAttributeTypedArgument.argumentType) &&
        Objects.equals(this.value, customAttributeTypedArgument.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(argumentType, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomAttributeTypedArgument {\n");
    
    sb.append("    argumentType: ").append(toIndentedString(argumentType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
