/*
 * CcsSso.ContactApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ModifiedSiteContactInfo
 */


public class ModifiedSiteContactInfo {
  @SerializedName("contactPointId")
  private Integer contactPointId = null;

  @SerializedName("siteContactId")
  private Integer siteContactId = null;

  @SerializedName("organisationId")
  private Integer organisationId = null;

  @SerializedName("ciiOrgId")
  private String ciiOrgId = null;

  public ModifiedSiteContactInfo contactPointId(Integer contactPointId) {
    this.contactPointId = contactPointId;
    return this;
  }

   /**
   * Get contactPointId
   * @return contactPointId
  **/
  @Schema(description = "")
  public Integer getContactPointId() {
    return contactPointId;
  }

  public void setContactPointId(Integer contactPointId) {
    this.contactPointId = contactPointId;
  }

  public ModifiedSiteContactInfo siteContactId(Integer siteContactId) {
    this.siteContactId = siteContactId;
    return this;
  }

   /**
   * Get siteContactId
   * @return siteContactId
  **/
  @Schema(description = "")
  public Integer getSiteContactId() {
    return siteContactId;
  }

  public void setSiteContactId(Integer siteContactId) {
    this.siteContactId = siteContactId;
  }

  public ModifiedSiteContactInfo organisationId(Integer organisationId) {
    this.organisationId = organisationId;
    return this;
  }

   /**
   * Get organisationId
   * @return organisationId
  **/
  @Schema(description = "")
  public Integer getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(Integer organisationId) {
    this.organisationId = organisationId;
  }

  public ModifiedSiteContactInfo ciiOrgId(String ciiOrgId) {
    this.ciiOrgId = ciiOrgId;
    return this;
  }

   /**
   * Get ciiOrgId
   * @return ciiOrgId
  **/
  @Schema(description = "")
  public String getCiiOrgId() {
    return ciiOrgId;
  }

  public void setCiiOrgId(String ciiOrgId) {
    this.ciiOrgId = ciiOrgId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifiedSiteContactInfo modifiedSiteContactInfo = (ModifiedSiteContactInfo) o;
    return Objects.equals(this.contactPointId, modifiedSiteContactInfo.contactPointId) &&
        Objects.equals(this.siteContactId, modifiedSiteContactInfo.siteContactId) &&
        Objects.equals(this.organisationId, modifiedSiteContactInfo.organisationId) &&
        Objects.equals(this.ciiOrgId, modifiedSiteContactInfo.ciiOrgId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactPointId, siteContactId, organisationId, ciiOrgId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifiedSiteContactInfo {\n");
    
    sb.append("    contactPointId: ").append(toIndentedString(contactPointId)).append("\n");
    sb.append("    siteContactId: ").append(toIndentedString(siteContactId)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    ciiOrgId: ").append(toIndentedString(ciiOrgId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
