/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OrganisationUserDto
 */


public class OrganisationUserDto {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ciiOrganisationId")
  private String ciiOrganisationId = null;

  @SerializedName("organisationLegalName")
  private String organisationLegalName = null;

  @SerializedName("isAdmin")
  private Boolean isAdmin = null;

  public OrganisationUserDto userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public OrganisationUserDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrganisationUserDto ciiOrganisationId(String ciiOrganisationId) {
    this.ciiOrganisationId = ciiOrganisationId;
    return this;
  }

   /**
   * Get ciiOrganisationId
   * @return ciiOrganisationId
  **/
  @Schema(description = "")
  public String getCiiOrganisationId() {
    return ciiOrganisationId;
  }

  public void setCiiOrganisationId(String ciiOrganisationId) {
    this.ciiOrganisationId = ciiOrganisationId;
  }

  public OrganisationUserDto organisationLegalName(String organisationLegalName) {
    this.organisationLegalName = organisationLegalName;
    return this;
  }

   /**
   * Get organisationLegalName
   * @return organisationLegalName
  **/
  @Schema(description = "")
  public String getOrganisationLegalName() {
    return organisationLegalName;
  }

  public void setOrganisationLegalName(String organisationLegalName) {
    this.organisationLegalName = organisationLegalName;
  }

  public OrganisationUserDto isAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

   /**
   * Get isAdmin
   * @return isAdmin
  **/
  @Schema(description = "")
  public Boolean isIsAdmin() {
    return isAdmin;
  }

  public void setIsAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationUserDto organisationUserDto = (OrganisationUserDto) o;
    return Objects.equals(this.userName, organisationUserDto.userName) &&
        Objects.equals(this.name, organisationUserDto.name) &&
        Objects.equals(this.ciiOrganisationId, organisationUserDto.ciiOrganisationId) &&
        Objects.equals(this.organisationLegalName, organisationUserDto.organisationLegalName) &&
        Objects.equals(this.isAdmin, organisationUserDto.isAdmin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, name, ciiOrganisationId, organisationLegalName, isAdmin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationUserDto {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ciiOrganisationId: ").append(toIndentedString(ciiOrganisationId)).append("\n");
    sb.append("    organisationLegalName: ").append(toIndentedString(organisationLegalName)).append("\n");
    sb.append("    isAdmin: ").append(toIndentedString(isAdmin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
