/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.OrganisationRole;
import uk.gov.ccs.swagger.sso.model.RoleEligibleTradeType;
/**
 * OrganisationAutoValidationRoleUpdate
 */


public class OrganisationAutoValidationRoleUpdate {
  @SerializedName("orgType")
  private RoleEligibleTradeType orgType = null;

  @SerializedName("rolesToAdd")
  private List<OrganisationRole> rolesToAdd = null;

  @SerializedName("rolesToDelete")
  private List<OrganisationRole> rolesToDelete = null;

  @SerializedName("rolesToAutoValid")
  private List<OrganisationRole> rolesToAutoValid = null;

  @SerializedName("companyHouseId")
  private String companyHouseId = null;

  public OrganisationAutoValidationRoleUpdate orgType(RoleEligibleTradeType orgType) {
    this.orgType = orgType;
    return this;
  }

   /**
   * Get orgType
   * @return orgType
  **/
  @Schema(description = "")
  public RoleEligibleTradeType getOrgType() {
    return orgType;
  }

  public void setOrgType(RoleEligibleTradeType orgType) {
    this.orgType = orgType;
  }

  public OrganisationAutoValidationRoleUpdate rolesToAdd(List<OrganisationRole> rolesToAdd) {
    this.rolesToAdd = rolesToAdd;
    return this;
  }

  public OrganisationAutoValidationRoleUpdate addRolesToAddItem(OrganisationRole rolesToAddItem) {
    if (this.rolesToAdd == null) {
      this.rolesToAdd = new ArrayList<OrganisationRole>();
    }
    this.rolesToAdd.add(rolesToAddItem);
    return this;
  }

   /**
   * Get rolesToAdd
   * @return rolesToAdd
  **/
  @Schema(description = "")
  public List<OrganisationRole> getRolesToAdd() {
    return rolesToAdd;
  }

  public void setRolesToAdd(List<OrganisationRole> rolesToAdd) {
    this.rolesToAdd = rolesToAdd;
  }

  public OrganisationAutoValidationRoleUpdate rolesToDelete(List<OrganisationRole> rolesToDelete) {
    this.rolesToDelete = rolesToDelete;
    return this;
  }

  public OrganisationAutoValidationRoleUpdate addRolesToDeleteItem(OrganisationRole rolesToDeleteItem) {
    if (this.rolesToDelete == null) {
      this.rolesToDelete = new ArrayList<OrganisationRole>();
    }
    this.rolesToDelete.add(rolesToDeleteItem);
    return this;
  }

   /**
   * Get rolesToDelete
   * @return rolesToDelete
  **/
  @Schema(description = "")
  public List<OrganisationRole> getRolesToDelete() {
    return rolesToDelete;
  }

  public void setRolesToDelete(List<OrganisationRole> rolesToDelete) {
    this.rolesToDelete = rolesToDelete;
  }

  public OrganisationAutoValidationRoleUpdate rolesToAutoValid(List<OrganisationRole> rolesToAutoValid) {
    this.rolesToAutoValid = rolesToAutoValid;
    return this;
  }

  public OrganisationAutoValidationRoleUpdate addRolesToAutoValidItem(OrganisationRole rolesToAutoValidItem) {
    if (this.rolesToAutoValid == null) {
      this.rolesToAutoValid = new ArrayList<OrganisationRole>();
    }
    this.rolesToAutoValid.add(rolesToAutoValidItem);
    return this;
  }

   /**
   * Get rolesToAutoValid
   * @return rolesToAutoValid
  **/
  @Schema(description = "")
  public List<OrganisationRole> getRolesToAutoValid() {
    return rolesToAutoValid;
  }

  public void setRolesToAutoValid(List<OrganisationRole> rolesToAutoValid) {
    this.rolesToAutoValid = rolesToAutoValid;
  }

  public OrganisationAutoValidationRoleUpdate companyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
    return this;
  }

   /**
   * Get companyHouseId
   * @return companyHouseId
  **/
  @Schema(description = "")
  public String getCompanyHouseId() {
    return companyHouseId;
  }

  public void setCompanyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationAutoValidationRoleUpdate organisationAutoValidationRoleUpdate = (OrganisationAutoValidationRoleUpdate) o;
    return Objects.equals(this.orgType, organisationAutoValidationRoleUpdate.orgType) &&
        Objects.equals(this.rolesToAdd, organisationAutoValidationRoleUpdate.rolesToAdd) &&
        Objects.equals(this.rolesToDelete, organisationAutoValidationRoleUpdate.rolesToDelete) &&
        Objects.equals(this.rolesToAutoValid, organisationAutoValidationRoleUpdate.rolesToAutoValid) &&
        Objects.equals(this.companyHouseId, organisationAutoValidationRoleUpdate.companyHouseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orgType, rolesToAdd, rolesToDelete, rolesToAutoValid, companyHouseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationAutoValidationRoleUpdate {\n");
    
    sb.append("    orgType: ").append(toIndentedString(orgType)).append("\n");
    sb.append("    rolesToAdd: ").append(toIndentedString(rolesToAdd)).append("\n");
    sb.append("    rolesToDelete: ").append(toIndentedString(rolesToDelete)).append("\n");
    sb.append("    rolesToAutoValid: ").append(toIndentedString(rolesToAutoValid)).append("\n");
    sb.append("    companyHouseId: ").append(toIndentedString(companyHouseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
