/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import uk.gov.ccs.swagger.sso.model.RoleEligibleOrgType;
import uk.gov.ccs.swagger.sso.model.RoleEligibleSubscriptionType;
import uk.gov.ccs.swagger.sso.model.RoleEligibleTradeType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import uk.gov.ccs.swagger.sso.JSON;

/**
 * OrganisationRole
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrganisationRole {
  public static final String SERIALIZED_NAME_ROLE_ID = "roleId";
  @SerializedName(SERIALIZED_NAME_ROLE_ID)
  private Integer roleId;

  public static final String SERIALIZED_NAME_ROLE_KEY = "roleKey";
  @SerializedName(SERIALIZED_NAME_ROLE_KEY)
  private String roleKey;

  public static final String SERIALIZED_NAME_ROLE_NAME = "roleName";
  @SerializedName(SERIALIZED_NAME_ROLE_NAME)
  private String roleName;

  public static final String SERIALIZED_NAME_SERVICE_NAME = "serviceName";
  @SerializedName(SERIALIZED_NAME_SERVICE_NAME)
  private String serviceName;

  public static final String SERIALIZED_NAME_ORG_TYPE_ELIGIBILITY = "orgTypeEligibility";
  @SerializedName(SERIALIZED_NAME_ORG_TYPE_ELIGIBILITY)
  private RoleEligibleOrgType orgTypeEligibility;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_TYPE_ELIGIBILITY = "subscriptionTypeEligibility";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_TYPE_ELIGIBILITY)
  private RoleEligibleSubscriptionType subscriptionTypeEligibility;

  public static final String SERIALIZED_NAME_TRADE_ELIGIBILITY = "tradeEligibility";
  @SerializedName(SERIALIZED_NAME_TRADE_ELIGIBILITY)
  private RoleEligibleTradeType tradeEligibility;

  public OrganisationRole() { 
  }

  public OrganisationRole roleId(Integer roleId) {
    
    this.roleId = roleId;
    return this;
  }

   /**
   * Get roleId
   * @return roleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getRoleId() {
    return roleId;
  }


  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }


  public OrganisationRole roleKey(String roleKey) {
    
    this.roleKey = roleKey;
    return this;
  }

   /**
   * Get roleKey
   * @return roleKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoleKey() {
    return roleKey;
  }


  public void setRoleKey(String roleKey) {
    this.roleKey = roleKey;
  }


  public OrganisationRole roleName(String roleName) {
    
    this.roleName = roleName;
    return this;
  }

   /**
   * Get roleName
   * @return roleName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoleName() {
    return roleName;
  }


  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }


  public OrganisationRole serviceName(String serviceName) {
    
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceName() {
    return serviceName;
  }


  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }


  public OrganisationRole orgTypeEligibility(RoleEligibleOrgType orgTypeEligibility) {
    
    this.orgTypeEligibility = orgTypeEligibility;
    return this;
  }

   /**
   * Get orgTypeEligibility
   * @return orgTypeEligibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RoleEligibleOrgType getOrgTypeEligibility() {
    return orgTypeEligibility;
  }


  public void setOrgTypeEligibility(RoleEligibleOrgType orgTypeEligibility) {
    this.orgTypeEligibility = orgTypeEligibility;
  }


  public OrganisationRole subscriptionTypeEligibility(RoleEligibleSubscriptionType subscriptionTypeEligibility) {
    
    this.subscriptionTypeEligibility = subscriptionTypeEligibility;
    return this;
  }

   /**
   * Get subscriptionTypeEligibility
   * @return subscriptionTypeEligibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RoleEligibleSubscriptionType getSubscriptionTypeEligibility() {
    return subscriptionTypeEligibility;
  }


  public void setSubscriptionTypeEligibility(RoleEligibleSubscriptionType subscriptionTypeEligibility) {
    this.subscriptionTypeEligibility = subscriptionTypeEligibility;
  }


  public OrganisationRole tradeEligibility(RoleEligibleTradeType tradeEligibility) {
    
    this.tradeEligibility = tradeEligibility;
    return this;
  }

   /**
   * Get tradeEligibility
   * @return tradeEligibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RoleEligibleTradeType getTradeEligibility() {
    return tradeEligibility;
  }


  public void setTradeEligibility(RoleEligibleTradeType tradeEligibility) {
    this.tradeEligibility = tradeEligibility;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationRole organisationRole = (OrganisationRole) o;
    return Objects.equals(this.roleId, organisationRole.roleId) &&
        Objects.equals(this.roleKey, organisationRole.roleKey) &&
        Objects.equals(this.roleName, organisationRole.roleName) &&
        Objects.equals(this.serviceName, organisationRole.serviceName) &&
        Objects.equals(this.orgTypeEligibility, organisationRole.orgTypeEligibility) &&
        Objects.equals(this.subscriptionTypeEligibility, organisationRole.subscriptionTypeEligibility) &&
        Objects.equals(this.tradeEligibility, organisationRole.tradeEligibility);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleId, roleKey, roleName, serviceName, orgTypeEligibility, subscriptionTypeEligibility, tradeEligibility);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationRole {\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    roleKey: ").append(toIndentedString(roleKey)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    orgTypeEligibility: ").append(toIndentedString(orgTypeEligibility)).append("\n");
    sb.append("    subscriptionTypeEligibility: ").append(toIndentedString(subscriptionTypeEligibility)).append("\n");
    sb.append("    tradeEligibility: ").append(toIndentedString(tradeEligibility)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("roleId");
    openapiFields.add("roleKey");
    openapiFields.add("roleName");
    openapiFields.add("serviceName");
    openapiFields.add("orgTypeEligibility");
    openapiFields.add("subscriptionTypeEligibility");
    openapiFields.add("tradeEligibility");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OrganisationRole
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OrganisationRole.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganisationRole is not found in the empty JSON string", OrganisationRole.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OrganisationRole.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganisationRole` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("roleKey") != null && !jsonObj.get("roleKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `roleKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("roleKey").toString()));
      }
      if (jsonObj.get("roleName") != null && !jsonObj.get("roleName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `roleName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("roleName").toString()));
      }
      if (jsonObj.get("serviceName") != null && !jsonObj.get("serviceName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganisationRole.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganisationRole' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganisationRole> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganisationRole.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganisationRole>() {
           @Override
           public void write(JsonWriter out, OrganisationRole value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganisationRole read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrganisationRole given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrganisationRole
  * @throws IOException if the JSON string is invalid with respect to OrganisationRole
  */
  public static OrganisationRole fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganisationRole.class);
  }

 /**
  * Convert an instance of OrganisationRole to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

