/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.OrganisationRole;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import uk.gov.ccs.swagger.sso.JSON;

/**
 * OrganisationRoleUpdate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrganisationRoleUpdate {
  public static final String SERIALIZED_NAME_IS_BUYER = "isBuyer";
  @SerializedName(SERIALIZED_NAME_IS_BUYER)
  private Boolean isBuyer;

  public static final String SERIALIZED_NAME_ROLES_TO_ADD = "rolesToAdd";
  @SerializedName(SERIALIZED_NAME_ROLES_TO_ADD)
  private List<OrganisationRole> rolesToAdd = null;

  public static final String SERIALIZED_NAME_ROLES_TO_DELETE = "rolesToDelete";
  @SerializedName(SERIALIZED_NAME_ROLES_TO_DELETE)
  private List<OrganisationRole> rolesToDelete = null;

  public OrganisationRoleUpdate() { 
  }

  public OrganisationRoleUpdate isBuyer(Boolean isBuyer) {
    
    this.isBuyer = isBuyer;
    return this;
  }

   /**
   * Get isBuyer
   * @return isBuyer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsBuyer() {
    return isBuyer;
  }


  public void setIsBuyer(Boolean isBuyer) {
    this.isBuyer = isBuyer;
  }


  public OrganisationRoleUpdate rolesToAdd(List<OrganisationRole> rolesToAdd) {
    
    this.rolesToAdd = rolesToAdd;
    return this;
  }

  public OrganisationRoleUpdate addRolesToAddItem(OrganisationRole rolesToAddItem) {
    if (this.rolesToAdd == null) {
      this.rolesToAdd = new ArrayList<>();
    }
    this.rolesToAdd.add(rolesToAddItem);
    return this;
  }

   /**
   * Get rolesToAdd
   * @return rolesToAdd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OrganisationRole> getRolesToAdd() {
    return rolesToAdd;
  }


  public void setRolesToAdd(List<OrganisationRole> rolesToAdd) {
    this.rolesToAdd = rolesToAdd;
  }


  public OrganisationRoleUpdate rolesToDelete(List<OrganisationRole> rolesToDelete) {
    
    this.rolesToDelete = rolesToDelete;
    return this;
  }

  public OrganisationRoleUpdate addRolesToDeleteItem(OrganisationRole rolesToDeleteItem) {
    if (this.rolesToDelete == null) {
      this.rolesToDelete = new ArrayList<>();
    }
    this.rolesToDelete.add(rolesToDeleteItem);
    return this;
  }

   /**
   * Get rolesToDelete
   * @return rolesToDelete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<OrganisationRole> getRolesToDelete() {
    return rolesToDelete;
  }


  public void setRolesToDelete(List<OrganisationRole> rolesToDelete) {
    this.rolesToDelete = rolesToDelete;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationRoleUpdate organisationRoleUpdate = (OrganisationRoleUpdate) o;
    return Objects.equals(this.isBuyer, organisationRoleUpdate.isBuyer) &&
        Objects.equals(this.rolesToAdd, organisationRoleUpdate.rolesToAdd) &&
        Objects.equals(this.rolesToDelete, organisationRoleUpdate.rolesToDelete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isBuyer, rolesToAdd, rolesToDelete);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationRoleUpdate {\n");
    sb.append("    isBuyer: ").append(toIndentedString(isBuyer)).append("\n");
    sb.append("    rolesToAdd: ").append(toIndentedString(rolesToAdd)).append("\n");
    sb.append("    rolesToDelete: ").append(toIndentedString(rolesToDelete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isBuyer");
    openapiFields.add("rolesToAdd");
    openapiFields.add("rolesToDelete");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OrganisationRoleUpdate
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OrganisationRoleUpdate.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganisationRoleUpdate is not found in the empty JSON string", OrganisationRoleUpdate.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OrganisationRoleUpdate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganisationRoleUpdate` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayrolesToAdd = jsonObj.getAsJsonArray("rolesToAdd");
      if (jsonArrayrolesToAdd != null) {
        // ensure the json data is an array
        if (!jsonObj.get("rolesToAdd").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `rolesToAdd` to be an array in the JSON string but got `%s`", jsonObj.get("rolesToAdd").toString()));
        }

        // validate the optional field `rolesToAdd` (array)
        for (int i = 0; i < jsonArrayrolesToAdd.size(); i++) {
          OrganisationRole.validateJsonObject(jsonArrayrolesToAdd.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArrayrolesToDelete = jsonObj.getAsJsonArray("rolesToDelete");
      if (jsonArrayrolesToDelete != null) {
        // ensure the json data is an array
        if (!jsonObj.get("rolesToDelete").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `rolesToDelete` to be an array in the JSON string but got `%s`", jsonObj.get("rolesToDelete").toString()));
        }

        // validate the optional field `rolesToDelete` (array)
        for (int i = 0; i < jsonArrayrolesToDelete.size(); i++) {
          OrganisationRole.validateJsonObject(jsonArrayrolesToDelete.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganisationRoleUpdate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganisationRoleUpdate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganisationRoleUpdate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganisationRoleUpdate.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganisationRoleUpdate>() {
           @Override
           public void write(JsonWriter out, OrganisationRoleUpdate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganisationRoleUpdate read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrganisationRoleUpdate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrganisationRoleUpdate
  * @throws IOException if the JSON string is invalid with respect to OrganisationRoleUpdate
  */
  public static OrganisationRoleUpdate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganisationRoleUpdate.class);
  }

 /**
  * Convert an instance of OrganisationRoleUpdate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

