/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.ContactResponseInfo;
import uk.gov.ccs.swagger.sso.model.OrganisationDetailInfo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import uk.gov.ccs.swagger.sso.JSON;

/**
 * OrganisationContactInfoList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrganisationContactInfoList {
  public static final String SERIALIZED_NAME_DETAIL = "detail";
  @SerializedName(SERIALIZED_NAME_DETAIL)
  private OrganisationDetailInfo detail;

  public static final String SERIALIZED_NAME_CONTACT_POINTS = "contactPoints";
  @SerializedName(SERIALIZED_NAME_CONTACT_POINTS)
  private List<ContactResponseInfo> contactPoints = null;

  public OrganisationContactInfoList() { 
  }

  public OrganisationContactInfoList detail(OrganisationDetailInfo detail) {
    
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OrganisationDetailInfo getDetail() {
    return detail;
  }


  public void setDetail(OrganisationDetailInfo detail) {
    this.detail = detail;
  }


  public OrganisationContactInfoList contactPoints(List<ContactResponseInfo> contactPoints) {
    
    this.contactPoints = contactPoints;
    return this;
  }

  public OrganisationContactInfoList addContactPointsItem(ContactResponseInfo contactPointsItem) {
    if (this.contactPoints == null) {
      this.contactPoints = new ArrayList<>();
    }
    this.contactPoints.add(contactPointsItem);
    return this;
  }

   /**
   * Get contactPoints
   * @return contactPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ContactResponseInfo> getContactPoints() {
    return contactPoints;
  }


  public void setContactPoints(List<ContactResponseInfo> contactPoints) {
    this.contactPoints = contactPoints;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationContactInfoList organisationContactInfoList = (OrganisationContactInfoList) o;
    return Objects.equals(this.detail, organisationContactInfoList.detail) &&
        Objects.equals(this.contactPoints, organisationContactInfoList.contactPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detail, contactPoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationContactInfoList {\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    contactPoints: ").append(toIndentedString(contactPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("detail");
    openapiFields.add("contactPoints");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OrganisationContactInfoList
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OrganisationContactInfoList.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganisationContactInfoList is not found in the empty JSON string", OrganisationContactInfoList.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OrganisationContactInfoList.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganisationContactInfoList` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `detail`
      if (jsonObj.getAsJsonObject("detail") != null) {
        OrganisationDetailInfo.validateJsonObject(jsonObj.getAsJsonObject("detail"));
      }
      JsonArray jsonArraycontactPoints = jsonObj.getAsJsonArray("contactPoints");
      if (jsonArraycontactPoints != null) {
        // ensure the json data is an array
        if (!jsonObj.get("contactPoints").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `contactPoints` to be an array in the JSON string but got `%s`", jsonObj.get("contactPoints").toString()));
        }

        // validate the optional field `contactPoints` (array)
        for (int i = 0; i < jsonArraycontactPoints.size(); i++) {
          ContactResponseInfo.validateJsonObject(jsonArraycontactPoints.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganisationContactInfoList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganisationContactInfoList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganisationContactInfoList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganisationContactInfoList.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganisationContactInfoList>() {
           @Override
           public void write(JsonWriter out, OrganisationContactInfoList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganisationContactInfoList read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrganisationContactInfoList given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrganisationContactInfoList
  * @throws IOException if the JSON string is invalid with respect to OrganisationContactInfoList
  */
  public static OrganisationContactInfoList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganisationContactInfoList.class);
  }

 /**
  * Convert an instance of OrganisationContactInfoList to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

