/*
 * CcsSso.WrapperApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.OrganisationAddress;
import uk.gov.ccs.swagger.sso.model.OrganisationDetail;
import uk.gov.ccs.swagger.sso.model.OrganisationIdentifier;
/**
 * OrganisationProfileResponseInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-27T09:35:55.156031+01:00[Europe/London]")
public class OrganisationProfileResponseInfo {
  @SerializedName("identifier")
  private OrganisationIdentifier identifier = null;

  @SerializedName("additionalIdentifiers")
  private List<OrganisationIdentifier> additionalIdentifiers = null;

  @SerializedName("address")
  private OrganisationAddress address = null;

  @SerializedName("detail")
  private OrganisationDetail detail = null;

  public OrganisationProfileResponseInfo identifier(OrganisationIdentifier identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @Schema(description = "")
  public OrganisationIdentifier getIdentifier() {
    return identifier;
  }

  public void setIdentifier(OrganisationIdentifier identifier) {
    this.identifier = identifier;
  }

  public OrganisationProfileResponseInfo additionalIdentifiers(List<OrganisationIdentifier> additionalIdentifiers) {
    this.additionalIdentifiers = additionalIdentifiers;
    return this;
  }

  public OrganisationProfileResponseInfo addAdditionalIdentifiersItem(OrganisationIdentifier additionalIdentifiersItem) {
    if (this.additionalIdentifiers == null) {
      this.additionalIdentifiers = new ArrayList<OrganisationIdentifier>();
    }
    this.additionalIdentifiers.add(additionalIdentifiersItem);
    return this;
  }

   /**
   * Get additionalIdentifiers
   * @return additionalIdentifiers
  **/
  @Schema(description = "")
  public List<OrganisationIdentifier> getAdditionalIdentifiers() {
    return additionalIdentifiers;
  }

  public void setAdditionalIdentifiers(List<OrganisationIdentifier> additionalIdentifiers) {
    this.additionalIdentifiers = additionalIdentifiers;
  }

  public OrganisationProfileResponseInfo address(OrganisationAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public OrganisationAddress getAddress() {
    return address;
  }

  public void setAddress(OrganisationAddress address) {
    this.address = address;
  }

  public OrganisationProfileResponseInfo detail(OrganisationDetail detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @Schema(description = "")
  public OrganisationDetail getDetail() {
    return detail;
  }

  public void setDetail(OrganisationDetail detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationProfileResponseInfo organisationProfileResponseInfo = (OrganisationProfileResponseInfo) o;
    return Objects.equals(this.identifier, organisationProfileResponseInfo.identifier) &&
        Objects.equals(this.additionalIdentifiers, organisationProfileResponseInfo.additionalIdentifiers) &&
        Objects.equals(this.address, organisationProfileResponseInfo.address) &&
        Objects.equals(this.detail, organisationProfileResponseInfo.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, additionalIdentifiers, address, detail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationProfileResponseInfo {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    additionalIdentifiers: ").append(toIndentedString(additionalIdentifiers)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
