/*
 * CcsSso.OrganisationApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OrgEligibleIdentityProvider
 */


public class OrgEligibleIdentityProvider {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("connectionName")
  private String connectionName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("identityProviderId")
  private Integer identityProviderId = null;

  public OrgEligibleIdentityProvider id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public OrgEligibleIdentityProvider connectionName(String connectionName) {
    this.connectionName = connectionName;
    return this;
  }

   /**
   * Get connectionName
   * @return connectionName
  **/
  @Schema(description = "")
  public String getConnectionName() {
    return connectionName;
  }

  public void setConnectionName(String connectionName) {
    this.connectionName = connectionName;
  }

  public OrgEligibleIdentityProvider name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrgEligibleIdentityProvider identityProviderId(Integer identityProviderId) {
    this.identityProviderId = identityProviderId;
    return this;
  }

   /**
   * Get identityProviderId
   * @return identityProviderId
  **/
  @Schema(description = "")
  public Integer getIdentityProviderId() {
    return identityProviderId;
  }

  public void setIdentityProviderId(Integer identityProviderId) {
    this.identityProviderId = identityProviderId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgEligibleIdentityProvider orgEligibleIdentityProvider = (OrgEligibleIdentityProvider) o;
    return Objects.equals(this.id, orgEligibleIdentityProvider.id) &&
        Objects.equals(this.connectionName, orgEligibleIdentityProvider.connectionName) &&
        Objects.equals(this.name, orgEligibleIdentityProvider.name) &&
        Objects.equals(this.identityProviderId, orgEligibleIdentityProvider.identityProviderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, connectionName, name, identityProviderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgEligibleIdentityProvider {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    connectionName: ").append(toIndentedString(connectionName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identityProviderId: ").append(toIndentedString(identityProviderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
