/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RoleEligibleSubscriptionType
 */
@JsonAdapter(RoleEligibleSubscriptionType.Adapter.class)
public enum RoleEligibleSubscriptionType {
  
  NUMBER_0(0),
  
  NUMBER_1(1);

  private Integer value;

  RoleEligibleSubscriptionType(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RoleEligibleSubscriptionType fromValue(Integer value) {
    for (RoleEligibleSubscriptionType b : RoleEligibleSubscriptionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RoleEligibleSubscriptionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final RoleEligibleSubscriptionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RoleEligibleSubscriptionType read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return RoleEligibleSubscriptionType.fromValue(value);
    }
  }
}

