/*
 * CcsSso.UserApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.OrganisationRole;
/**
 * UpdateUserAccessRoleRequest
 */


public class UpdateUserAccessRoleRequest {
  @SerializedName("roles")
  private List<OrganisationRole> roles = null;

  @SerializedName("roleIdsToUpdate")
  private List<Integer> roleIdsToUpdate = null;

  public UpdateUserAccessRoleRequest roles(List<OrganisationRole> roles) {
    this.roles = roles;
    return this;
  }

  public UpdateUserAccessRoleRequest addRolesItem(OrganisationRole rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<OrganisationRole>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @Schema(description = "")
  public List<OrganisationRole> getRoles() {
    return roles;
  }

  public void setRoles(List<OrganisationRole> roles) {
    this.roles = roles;
  }

  public UpdateUserAccessRoleRequest roleIdsToUpdate(List<Integer> roleIdsToUpdate) {
    this.roleIdsToUpdate = roleIdsToUpdate;
    return this;
  }

  public UpdateUserAccessRoleRequest addRoleIdsToUpdateItem(Integer roleIdsToUpdateItem) {
    if (this.roleIdsToUpdate == null) {
      this.roleIdsToUpdate = new ArrayList<Integer>();
    }
    this.roleIdsToUpdate.add(roleIdsToUpdateItem);
    return this;
  }

   /**
   * Get roleIdsToUpdate
   * @return roleIdsToUpdate
  **/
  @Schema(description = "")
  public List<Integer> getRoleIdsToUpdate() {
    return roleIdsToUpdate;
  }

  public void setRoleIdsToUpdate(List<Integer> roleIdsToUpdate) {
    this.roleIdsToUpdate = roleIdsToUpdate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserAccessRoleRequest updateUserAccessRoleRequest = (UpdateUserAccessRoleRequest) o;
    return Objects.equals(this.roles, updateUserAccessRoleRequest.roles) &&
        Objects.equals(this.roleIdsToUpdate, updateUserAccessRoleRequest.roleIdsToUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roles, roleIdsToUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserAccessRoleRequest {\n");
    
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    roleIdsToUpdate: ").append(toIndentedString(roleIdsToUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
