/*
 * CcsSso.WrapperApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import uk.gov.ccs.swagger.sso.JSON;

/**
 * UserRequestDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserRequestDetail {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_GROUP_IDS = "groupIds";
  @SerializedName(SERIALIZED_NAME_GROUP_IDS)
  private List<Integer> groupIds = null;

  public static final String SERIALIZED_NAME_ROLE_IDS = "roleIds";
  @SerializedName(SERIALIZED_NAME_ROLE_IDS)
  private List<Integer> roleIds = null;

  public static final String SERIALIZED_NAME_IDENTITY_PROVIDER_IDS = "identityProviderIds";
  @SerializedName(SERIALIZED_NAME_IDENTITY_PROVIDER_IDS)
  private List<Integer> identityProviderIds = null;

  public UserRequestDetail() { 
  }

  public UserRequestDetail id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public UserRequestDetail groupIds(List<Integer> groupIds) {
    
    this.groupIds = groupIds;
    return this;
  }

  public UserRequestDetail addGroupIdsItem(Integer groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

   /**
   * Get groupIds
   * @return groupIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getGroupIds() {
    return groupIds;
  }


  public void setGroupIds(List<Integer> groupIds) {
    this.groupIds = groupIds;
  }


  public UserRequestDetail roleIds(List<Integer> roleIds) {
    
    this.roleIds = roleIds;
    return this;
  }

  public UserRequestDetail addRoleIdsItem(Integer roleIdsItem) {
    if (this.roleIds == null) {
      this.roleIds = new ArrayList<>();
    }
    this.roleIds.add(roleIdsItem);
    return this;
  }

   /**
   * Get roleIds
   * @return roleIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getRoleIds() {
    return roleIds;
  }


  public void setRoleIds(List<Integer> roleIds) {
    this.roleIds = roleIds;
  }


  public UserRequestDetail identityProviderIds(List<Integer> identityProviderIds) {
    
    this.identityProviderIds = identityProviderIds;
    return this;
  }

  public UserRequestDetail addIdentityProviderIdsItem(Integer identityProviderIdsItem) {
    if (this.identityProviderIds == null) {
      this.identityProviderIds = new ArrayList<>();
    }
    this.identityProviderIds.add(identityProviderIdsItem);
    return this;
  }

   /**
   * Get identityProviderIds
   * @return identityProviderIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getIdentityProviderIds() {
    return identityProviderIds;
  }


  public void setIdentityProviderIds(List<Integer> identityProviderIds) {
    this.identityProviderIds = identityProviderIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRequestDetail userRequestDetail = (UserRequestDetail) o;
    return Objects.equals(this.id, userRequestDetail.id) &&
        Objects.equals(this.groupIds, userRequestDetail.groupIds) &&
        Objects.equals(this.roleIds, userRequestDetail.roleIds) &&
        Objects.equals(this.identityProviderIds, userRequestDetail.identityProviderIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, groupIds, roleIds, identityProviderIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRequestDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("    roleIds: ").append(toIndentedString(roleIds)).append("\n");
    sb.append("    identityProviderIds: ").append(toIndentedString(identityProviderIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("groupIds");
    openapiFields.add("roleIds");
    openapiFields.add("identityProviderIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UserRequestDetail
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (UserRequestDetail.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserRequestDetail is not found in the empty JSON string", UserRequestDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UserRequestDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UserRequestDetail` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("groupIds") != null && !jsonObj.get("groupIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `groupIds` to be an array in the JSON string but got `%s`", jsonObj.get("groupIds").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("roleIds") != null && !jsonObj.get("roleIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `roleIds` to be an array in the JSON string but got `%s`", jsonObj.get("roleIds").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("identityProviderIds") != null && !jsonObj.get("identityProviderIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `identityProviderIds` to be an array in the JSON string but got `%s`", jsonObj.get("identityProviderIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserRequestDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserRequestDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserRequestDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserRequestDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<UserRequestDetail>() {
           @Override
           public void write(JsonWriter out, UserRequestDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserRequestDetail read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UserRequestDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UserRequestDetail
  * @throws IOException if the JSON string is invalid with respect to UserRequestDetail
  */
  public static UserRequestDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserRequestDetail.class);
  }

 /**
  * Convert an instance of UserRequestDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

