/*
 * CcsSso.UserApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import uk.gov.ccs.swagger.sso.model.UserServiceRoleGroupResponseDetail;
/**
 * UserProfileServiceRoleGroupResponseInfo
 */


public class UserProfileServiceRoleGroupResponseInfo {
  @SerializedName("userName")
  private String userName = null;

  @SerializedName("organisationId")
  private String organisationId = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("mfaEnabled")
  private Boolean mfaEnabled = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("accountVerified")
  private Boolean accountVerified = null;

  @SerializedName("sendUserRegistrationEmail")
  private Boolean sendUserRegistrationEmail = null;

  @SerializedName("originOrganisationName")
  private String originOrganisationName = null;

  @SerializedName("companyHouseId")
  private String companyHouseId = null;

  @SerializedName("isAdminUser")
  private Boolean isAdminUser = null;

  @SerializedName("detail")
  private UserServiceRoleGroupResponseDetail detail = null;

  public UserProfileServiceRoleGroupResponseInfo userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UserProfileServiceRoleGroupResponseInfo organisationId(String organisationId) {
    this.organisationId = organisationId;
    return this;
  }

   /**
   * Get organisationId
   * @return organisationId
  **/
  @Schema(description = "")
  public String getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
  }

  public UserProfileServiceRoleGroupResponseInfo firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @Schema(description = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserProfileServiceRoleGroupResponseInfo lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserProfileServiceRoleGroupResponseInfo title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public UserProfileServiceRoleGroupResponseInfo mfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
    return this;
  }

   /**
   * Get mfaEnabled
   * @return mfaEnabled
  **/
  @Schema(description = "")
  public Boolean isMfaEnabled() {
    return mfaEnabled;
  }

  public void setMfaEnabled(Boolean mfaEnabled) {
    this.mfaEnabled = mfaEnabled;
  }

  public UserProfileServiceRoleGroupResponseInfo password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @Schema(description = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserProfileServiceRoleGroupResponseInfo accountVerified(Boolean accountVerified) {
    this.accountVerified = accountVerified;
    return this;
  }

   /**
   * Get accountVerified
   * @return accountVerified
  **/
  @Schema(description = "")
  public Boolean isAccountVerified() {
    return accountVerified;
  }

  public void setAccountVerified(Boolean accountVerified) {
    this.accountVerified = accountVerified;
  }

  public UserProfileServiceRoleGroupResponseInfo sendUserRegistrationEmail(Boolean sendUserRegistrationEmail) {
    this.sendUserRegistrationEmail = sendUserRegistrationEmail;
    return this;
  }

   /**
   * Get sendUserRegistrationEmail
   * @return sendUserRegistrationEmail
  **/
  @Schema(description = "")
  public Boolean isSendUserRegistrationEmail() {
    return sendUserRegistrationEmail;
  }

  public void setSendUserRegistrationEmail(Boolean sendUserRegistrationEmail) {
    this.sendUserRegistrationEmail = sendUserRegistrationEmail;
  }

  public UserProfileServiceRoleGroupResponseInfo originOrganisationName(String originOrganisationName) {
    this.originOrganisationName = originOrganisationName;
    return this;
  }

   /**
   * Get originOrganisationName
   * @return originOrganisationName
  **/
  @Schema(description = "")
  public String getOriginOrganisationName() {
    return originOrganisationName;
  }

  public void setOriginOrganisationName(String originOrganisationName) {
    this.originOrganisationName = originOrganisationName;
  }

  public UserProfileServiceRoleGroupResponseInfo companyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
    return this;
  }

   /**
   * Get companyHouseId
   * @return companyHouseId
  **/
  @Schema(description = "")
  public String getCompanyHouseId() {
    return companyHouseId;
  }

  public void setCompanyHouseId(String companyHouseId) {
    this.companyHouseId = companyHouseId;
  }

  public UserProfileServiceRoleGroupResponseInfo isAdminUser(Boolean isAdminUser) {
    this.isAdminUser = isAdminUser;
    return this;
  }

   /**
   * Get isAdminUser
   * @return isAdminUser
  **/
  @Schema(description = "")
  public Boolean isIsAdminUser() {
    return isAdminUser;
  }

  public void setIsAdminUser(Boolean isAdminUser) {
    this.isAdminUser = isAdminUser;
  }

  public UserProfileServiceRoleGroupResponseInfo detail(UserServiceRoleGroupResponseDetail detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @Schema(description = "")
  public UserServiceRoleGroupResponseDetail getDetail() {
    return detail;
  }

  public void setDetail(UserServiceRoleGroupResponseDetail detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileServiceRoleGroupResponseInfo userProfileServiceRoleGroupResponseInfo = (UserProfileServiceRoleGroupResponseInfo) o;
    return Objects.equals(this.userName, userProfileServiceRoleGroupResponseInfo.userName) &&
        Objects.equals(this.organisationId, userProfileServiceRoleGroupResponseInfo.organisationId) &&
        Objects.equals(this.firstName, userProfileServiceRoleGroupResponseInfo.firstName) &&
        Objects.equals(this.lastName, userProfileServiceRoleGroupResponseInfo.lastName) &&
        Objects.equals(this.title, userProfileServiceRoleGroupResponseInfo.title) &&
        Objects.equals(this.mfaEnabled, userProfileServiceRoleGroupResponseInfo.mfaEnabled) &&
        Objects.equals(this.password, userProfileServiceRoleGroupResponseInfo.password) &&
        Objects.equals(this.accountVerified, userProfileServiceRoleGroupResponseInfo.accountVerified) &&
        Objects.equals(this.sendUserRegistrationEmail, userProfileServiceRoleGroupResponseInfo.sendUserRegistrationEmail) &&
        Objects.equals(this.originOrganisationName, userProfileServiceRoleGroupResponseInfo.originOrganisationName) &&
        Objects.equals(this.companyHouseId, userProfileServiceRoleGroupResponseInfo.companyHouseId) &&
        Objects.equals(this.isAdminUser, userProfileServiceRoleGroupResponseInfo.isAdminUser) &&
        Objects.equals(this.detail, userProfileServiceRoleGroupResponseInfo.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, organisationId, firstName, lastName, title, mfaEnabled, password, accountVerified, sendUserRegistrationEmail, originOrganisationName, companyHouseId, isAdminUser, detail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileServiceRoleGroupResponseInfo {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    mfaEnabled: ").append(toIndentedString(mfaEnabled)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    accountVerified: ").append(toIndentedString(accountVerified)).append("\n");
    sb.append("    sendUserRegistrationEmail: ").append(toIndentedString(sendUserRegistrationEmail)).append("\n");
    sb.append("    originOrganisationName: ").append(toIndentedString(originOrganisationName)).append("\n");
    sb.append("    companyHouseId: ").append(toIndentedString(companyHouseId)).append("\n");
    sb.append("    isAdminUser: ").append(toIndentedString(isAdminUser)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
