/*
 * CcsSso.UserApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package uk.gov.ccs.swagger.sso.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import uk.gov.ccs.swagger.sso.model.UserNameList;
/**
 * UserNameListResponse
 */


public class UserNameListResponse {
  @SerializedName("userNameList")
  private List<UserNameList> userNameList = null;

  public UserNameListResponse userNameList(List<UserNameList> userNameList) {
    this.userNameList = userNameList;
    return this;
  }

  public UserNameListResponse addUserNameListItem(UserNameList userNameListItem) {
    if (this.userNameList == null) {
      this.userNameList = new ArrayList<UserNameList>();
    }
    this.userNameList.add(userNameListItem);
    return this;
  }

   /**
   * Get userNameList
   * @return userNameList
  **/
  @Schema(description = "")
  public List<UserNameList> getUserNameList() {
    return userNameList;
  }

  public void setUserNameList(List<UserNameList> userNameList) {
    this.userNameList = userNameList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserNameListResponse userNameListResponse = (UserNameListResponse) o;
    return Objects.equals(this.userNameList, userNameListResponse.userNameList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userNameList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserNameListResponse {\n");
    
    sb.append("    userNameList: ").append(toIndentedString(userNameList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
