/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package uk.gov.ccs.swagger.dataMigration.api;

import java.util.List;
import uk.gov.ccs.swagger.dataMigration.model.Organisation;
import uk.gov.ccs.swagger.dataMigration.model.Summary;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "data-migration", description = "the data-migration API")
public interface DataMigrationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /data-migration/migrate/format/{fileFormat} : A generic endpoint for regisering organisations and users
     *
     * @param fileFormat File format - CSV/JSON (required)
     * @param docId file location e.g. /path (optional)
     * @param organisation  (optional)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Duplicate resource (status code 409)
     *         or Too Many Requests (status code 429)
     *         or Internal Server Error (status code 500)
     *         or Not Implemented (status code 501)
     *         or Bad Gateway (status code 502)
     *         or Service Unavailable/Limit Exceeded (status code 503)
     *         or Gateway Timeout (status code 504)
     *         or HTTP Version Not Supported (status code 505)
     */
    @Operation(
        operationId = "appMigrateOrg",
        summary = "A generic endpoint for regisering organisations and users",
        tags = { "datamigration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Summary.class))
            }),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "400", description = "Bad Request"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "409", description = "Duplicate resource"),
            @ApiResponse(responseCode = "429", description = "Too Many Requests"),
            @ApiResponse(responseCode = "500", description = "Internal Server Error"),
            @ApiResponse(responseCode = "501", description = "Not Implemented"),
            @ApiResponse(responseCode = "502", description = "Bad Gateway"),
            @ApiResponse(responseCode = "503", description = "Service Unavailable/Limit Exceeded"),
            @ApiResponse(responseCode = "504", description = "Gateway Timeout"),
            @ApiResponse(responseCode = "505", description = "HTTP Version Not Supported")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/data-migration/migrate/format/{fileFormat}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<Summary>> appMigrateOrg(
        @Parameter(name = "fileFormat", description = "File format - CSV/JSON", required = true) @PathVariable("fileFormat") String fileFormat,
        @Parameter(name = "docId", description = "file location e.g. /path") @Valid @RequestParam(value = "docId", required = false) String docId,
        @Parameter(name = "Organisation", description = "") @Valid @RequestBody(required = false) List<Organisation> organisation
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"Status\" : [ null, null ], \"scheme-id\" : \"GB-COH\", \"rightToBuy\" : true, \"identifier-id\" : \"100009655\", \"orgRoles\" : [ { \"name\" : \"RMI\" }, { \"name\" : \"RMI\" } ], \"user\" : [ { \"firstName\" : \"Joe\", \"lastName\" : \"Bloggs\", \"userRoles\" : [ { \"name\" : \"RMI User\" }, { \"name\" : \"RMI User\" } ], \"contactEmail\" : \"abc@somewhere.org\", \"title\" : \"Mr\", \"email\" : \"joe.bloggs@kier.com\", \"status\" : [ null, null ] }, { \"firstName\" : \"Joe\", \"lastName\" : \"Bloggs\", \"userRoles\" : [ { \"name\" : \"RMI User\" }, { \"name\" : \"RMI User\" } ], \"contactEmail\" : \"abc@somewhere.org\", \"title\" : \"Mr\", \"email\" : \"joe.bloggs@kier.com\", \"status\" : [ null, null ] } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
